### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by helmigsimon** [rish-16/gpt2client#1]
After installing the module via pip, I ran the following:

`from gpt2_client import GPT2Client`

And obtained the following error:
"""
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
SystemError: <class '_frozen_importlib._ModuleLockManager'> returned a result with an error set
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import
2019-08-11 12:24:16.856395: F tensorflow/python/lib/core/bfloat16.cc:675] Check failed: PyBfloat16_Type.tp_base != nullptr 
Abort trap: 6
"""

**Comment by rish-16** [comment]
Hey there, I'll go check it out. Thanks for informing. Never ran into this bug during testing

**Comment by rickwierenga** [comment]
Make sure you're running python 3.

```bash
python3 --version # should output some number.
```

It looks like numpy was not installed correctly. Can you try reinstalling it? https://pypi.org/project/numpy/

```bash
python3 -m pip install --upgrade --force-reinstall numpy
```

If this doesn't solve the issue, would you mind sharing your operating system and version?
