### ISSUE TITLE
Error when trying to use force download param 

### ISSUE THREAD

**Issue by redditTroll** [rish-16/gpt2client#10]
Re convo on reddit, tthis the error I get when trying to run the example 

Traceback (most recent call last):

File "machineLearning/RedditGTP2/labs.py", line 4, in <module>

gpt2.download_model(force_download=False) # Use cached versions

TypeError: download_model() got an unexpected keyword argument 'force_download'

Using Ubuntu 19.4

**Comment by rish-16** [comment]
Hello there,

The new update will no longer have the `force_download` parameter. It will instead automatically look for the cached weights and model checkpoints before downloading them (if absent, of course).

Thank you so much for your patience!
