### ISSUE TITLE
Support for the newest OpenAI 1.5B GPT-2 model

### ISSUE THREAD

**Issue by tarvos21** [rish-16/gpt2client#16]
**Is your feature request related to a problem? Please describe.**
Could it surrport the newest  OpenAI 1.5B GPT-2 model?

**Describe the solution you'd like**
Support for the newest OpenAI 1.5B GPT-2 model

**Describe alternatives you've considered**

**Additional context**

**Comment by rish-16** [comment]
Hello there! I just launched V2.1! It comes with support for the new model + allows you to encode and decode text sequences.

Hope this helps :)
