### ISSUE TITLE
i want to make pb file of the 1558M with inference

### ISSUE THREAD

**Issue by pragnakalpdev6** [rish-16/gpt2client#18]
hi,
i am trying to make pb file for the large models 1558M/774M but unable to do so.
And after making PB file i want to do inference for text generation

**Comment by rish-16** [comment]
Hello there,
Thank you for using `gpt2-client`! Currently, the module does not feature a way to convert the model checkpoints to a `.pb` file automatically. It'd be awesome if you could create a feature request in the Issues tab with more information on what you'd like to do with it.

Cheers!
