### ISSUE TITLE
a little too realistic, not enough creativity. is there anyway to make this more creative?

### ISSUE THREAD

**Issue by pharrowboy** [rish-16/gpt2client#22]
so i was finetuning the  345M model based on a dataset of the harry potter books. and i noticed it started spitting out lines from the book. this is way too realistic. is there anyway to add creativity to the model or something? 

here's a sample text from the model that was generated, and if any of you have read the harry potter books, you'd know that this did happen. 

"“Not to worry, I can sort him out!” he yelled, advancing on
Dudley with his wand outstretched, but Aunt Petunia screamed
worse than ever and threw herself on top of Dudley, shielding him
from Mr. Weasley.
“No, really!” said Mr. Weasley desperately. “It’s a simple process —
it was the toffee — my son Fred — real practical joker — but it’s
only an Engorgement Charm — at least, I think it is — please, I can
correct it —”
But far from being reassured, the Dursleys became more panicstricken;
Aunt Petunia was sobbing hysterically, tugging Dudley’s
tongue as though determined to rip it out; Dudley was sobbing, too,"

this AI is not very creative it seems.

**Comment by rish-16** [comment]
If I can recall correctly, this probably has to do with the temperature of the model. You can try tweaking it and see if it's more "creative"
