### ISSUE TITLE
How do I resume training from checkpoint

### ISSUE THREAD

**Issue by viveklse** [rish-16/gpt2client#26]
**Describe the bug**
How do I resume training from a checkpoint? Also, how do I save the trained model to my drive?

I am asking this because I know this package is downloading gpt2simple (Successfully installed **gpt-2-simple-0.6** gpt2-client-2.0 regex-2019.8.19 toposort-1.5) and using the following:
`gpt2.copy_checkpoint_to_gdrive(run_name=model-name')`
you can save your trained model to your drive.

Thanks

**Comment by rish-16** [comment]
Hey, for now, the package does not have a "resume from checkpoint" kind of method. Will put it on the list, though :)
