### ISSUE TITLE
Prompt + Custom dataset

### ISSUE THREAD

**Issue by ShaunLWM** [rish-16/gpt2client#27]
How do I generate text with prompts from custom trained data?

I have tried
```
my_corpus = './3cleewh.txt' # path to corpus
gpt2.finetune(my_corpus)
prompts = [
    "What do you think of the taxi driver?",
]

text = gpt2.generate_batch_from_prompts(prompts)
print (text)
```

But I think this generates text from its own corpus instead of mine. 
Thank you.

Edit: I tried replacing the files in 345M folder with my custom trained files, but the same problem occurs.

**Comment by rish-16** [comment]
Hey, 

Thanks for the headsup. Will look into this issue.
I'm still finding workarounds to a few internal problems.
