### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.contrib' for tensorflow >= 2

### ISSUE THREAD

**Issue by BAHorobet** [rish-16/gpt2client#28]
It doesn't seem to work with TensorFlow 2. Is there an update coming soon for the package?

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-8-07d02c54189c> in <module>
----> 1 from gpt2_client import GPT2Client

~\Anaconda3\envs\tensorflow-GPU\lib\site-packages\gpt2_client\__init__.py in <module>
----> 1 from gpt2_client.gpt2_client import GPT2Client

~\Anaconda3\envs\tensorflow-GPU\lib\site-packages\gpt2_client\gpt2_client.py in <module>
     11 
     12 import tensorflow as tf
---> 13 from tensorflow.contrib.training import HParams
     14 import numpy as np
     15 import gpt_2_simple as gpt2

ModuleNotFoundError: No module named 'tensorflow.contrib'

**Comment by codecrust** [comment]
Install tensor flow 1.15 and it goes away. Tensorflow.contrib was removed in v2 onwards.

**Comment by rish-16** [comment]
Hey, @BAHorobet 

The package is Tensorflow 1.1X only. Unfortunately, with school and work, I haven't had to time to switch to TF2.0

**Comment by BAHorobet** [comment]
Thanks, guys.

I understand @rish-16, do you have it in plan to upgrade it to TF2.0? I can see that Tensorflow.contrib was removed but there must be an alternative.

**Comment by rish-16** [comment]
@BAHorobet Yup, definitely! It's in the world. I'm slowly getting it done 😓 

Appreciate your patience :)
