### ISSUE TITLE
Specify the number of epochs when finetuning gpt2client

### ISSUE THREAD

**Issue by BrianMwangi21** [rish-16/gpt2client#34]
How many epochs does it take the gpt2client to fine tune and can one specify explicitly ?

I have been running on Colab and now it is at 177 and I am wondering how long I have to go yet. Thanks

**Comment by rish-16** [comment]
Hey there,

The finetuning feature of gpt2-client uses a third-party finetuning library called gpt2-simple. All the details on finetuning can be found there. So sorry for the delayed response – I haven't had the time to work on this project for a while.

Appreciate your patience!
