### ISSUE TITLE
Asking for tensorflow contrib module

### ISSUE THREAD

**Issue by jaytimbadia** [rish-16/gpt2client#36]
from gpt2_client import GPT2Client

gpt2 = GPT2Client('345M', save_dir='gptmodel')

gpt2.generate(interactive=True)
gpt2.generate(n_samples=4)

text = gpt2.generate(return_text=True)
print(text)

Traceback (most recent call last):
  File "scrape.py", line 1, in <module>
    from gpt2_client import GPT2Client
  File "C:\Users\jay.timbadia\black\lib\site-packages\gpt2_client\__init__.py", line 1, in <module>
    from gpt2_client.gpt2_client import GPT2Client
  File "C:\Users\jay.timbadia\black\lib\site-packages\gpt2_client\gpt2_client.py", line 13, in <module>
    from tensorflow.contrib.training import HParams
ModuleNotFoundError: No module named 'tensorflow.contrib'

I mean all deprendency were satisfied when it got installed right, why needs contrib module then? gpt2-client requires tensorflow 2.3.0 but I dont think it supports contrib?

**Comment by myanmccann** [comment]
Maybe try:
pip uninstall tensorflow
pip install tensorflow==1.14.0

**Comment by rish-16** [comment]
Hey!

So sorry for the delay in response. gpt2-client only supports TF 1.1X. I haven't had the time to convert it to TF2+. I'm not entirely sure when a possible fix is due. Will definitely keep you in the loop @jaytimbadia!

**Comment by ansible42** [comment]
Same error, and 1.14.0 gives me  HadoopFileSystem load error.
