### ISSUE TITLE
NoSuchBucket Error when downloading any model

### ISSUE THREAD

**Issue by pygeonburger** [rish-16/gpt2client#37]
**Describe the bug**
I can't download any proper model. The model files it downloads just all say pretty much this:

```
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist.</Message></Error>
```

Not sure if this is a programming bug or the servers these models are stored on are stuffed.

**To Reproduce**

The exact code I used:

```
from gpt2_client import GPT2Client

gpt2 = GPT2Client('117M')
gpt2.load_model(force_download=True) 
```

The output:

```
Downloading checkpoint: 1.00kit [00:00, 1.09Mit/s]
Downloading encoder.json: 1.00kit [00:00, 1.10Mit/s]
Downloading hparams.json: 1.00kit [00:00, 1.10Mit/s]
Downloading model.ckpt.data-00000-of-00001: 1.00kit [00:00, 1.07Mit/s]
Downloading model.ckpt.index: 1.00kit [00:00, 1.10Mit/s]
Downloading model.ckpt.meta: 1.00kit [00:00, 1.06Mit/s]
Downloading vocab.bpe: 1.00kit [00:00, 1.06Mit/s]
```

And they all have error messages.

**Expected behavior**
The models should be downloading properly without a NoSuchBucket error

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 20.04, Python 3.7

**Additional context**
Appreciate any help

**Comment by brunodpoliveira** [comment]
It seems like the gpt2.load_model() function is defective.

The https://storage.googleapis.com/gpt-2 bucket no longer exists

**Comment by rish-16** [comment]
Hello!

A recently-merged PR fixes this. The bucket URL has been updated :)

Appreciate your patience!
