### ISSUE TITLE
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by brunodpoliveira** [rish-16/gpt2client#38]
**Describe the bug**
Trying to follow the Google Colab Tutorial will result in this error: JSONDecodeError: Expecting value: line 1 column 1 (char 0)
when attempting to run block gpt2.generate(interactive=True)
**To Reproduce**
1. Executed following commands on the google colab notebook: 
2. !pip install gpt2-client
3. !pip install tensorflow==1.14
4. from gpt2_client import GPT2Client
5. from pprint import pprint
6. gpt2 = GPT2Client('117M')
7. gpt2.load_model()
8. !ls
9. !cd models/117M && ls
10. gpt2.generate(interactive=True)

**Expected behavior**
It should have given me a prompt to insert some text

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 on Oracle VM
 - Google Colab notebook: https://colab.research.google.com/drive/1RZwp1n6XeWxvhBjt1e3ATSOy4Mj9GEEl#scrollTo=8Ky6w8DsT2RH

**Comment by Xelef2000** [comment]
It seems like the load model function is defective.
All downloaded files only contain
`<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist.</Message></Error>`

**Comment by brunodpoliveira** [comment]
For whoever reads this, this repository (https://github.com/nshepperd/gpt-2) works correctly (tested on 17/march/2021)
