### ISSUE TITLE
What advantages does this have over gpt-2-simple?

### ISSUE THREAD

**Issue by minimaxir** [rish-16/gpt2client#8]
I see this package imports gpt-2-simple but also duplicates a lot of the functionality. Although that's permissible per the licensing, I'm not sure what the intent behind this project is.

**Comment by rish-16** [comment]
Hey there! gpt-2-simple is mainly meant for fine-tuning purposes (it's well known for that). got2-client, on the other hand, provides a holistic UI to interact with GPT-2 in the most seamless way possible.

To keep it simple, gpt2-client builds on top of gpt-2-simple and it's functionalities with some added features that have shown to be quite useful to some users. For more details as to how people are using it, You can check the Reddit thread here! 

https://www.reddit.com/r/MachineLearning/comments/coupe3/project_gpt2client_a_new_wrapper_for_gpt2/?utm_source=share&utm_medium=ios_app

Hope this helps!
