### ISSUE TITLE
New GPT 774M model + TPU

### ISSUE THREAD

**Issue by marcoaleixo** [rish-16/gpt2client#9]
They released a new model - https://openai.com/blog/gpt-2-6-month-follow-up/
And I think we will need TPU to use that model.
I'm trying to use the 345M with TPU using Colab, but when I change to TPU the code uses CPU.

**Comment by rish-16** [comment]
Hey there, thanks for the issue. I'll look into bringing the 774M model onboard. Will keep you updated.

Cheers

**Comment by rish-16** [comment]
Hello there! `gpt2-client` is now compatible with the 774M model! Thank you so much for waiting :)
